version: '3'

services:
  database:
    image: ivonet/mysql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_ROOT_HOST: '%'
    networks:
      - network
  redis:
    image: redis
    depends_on:
      - database
    networks:
      - network

  parer:
    build: ../parer
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: gunicorn --workers ${WORKERS} --bind 0.0.0.0:5000 --timeout 120 wsgi:app
    stdin_open: true
    tty: true
    depends_on:
      - redis
    networks:
      - network

  get_tasks:
    build: ../get_tasks
    env_file:
      - .env
    depends_on:
      - redis
    command: python3 get_tasks.py runworker
    networks:
      - network

  dashboard:
    build: ../rq_dashboard
    ports:
      - "9181:9181"
    command: rq-dashboard -H redis
    depends_on:
      - parer
    networks:
      - network

networks:
  network: {}
